CREATE TABLE CATEGORIES (
  category_id NUMERIC(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL
    PRIMARY KEY,
  category_name VARCHAR(64) NOT NULL,
  category_sum_product_price INT,
  category_sum_product_stock INT
);