-- PRODUITS
TRUNCATE TABLE PRODUITS;
DROP TABLE PRODUITS;

-- CATEGORIES
TRUNCATE TABLE CATEGORIES;
DROP TABLE CATEGORIES;

-- FACTURES
TRUNCATE TABLE FACTURE;
DROP TABLE FACTURE;

-- CLIENTS
TRUNCATE TABLE CLIENT;
DROP TABLE CLIENT;

-- VIEWS
DROP VIEW VCategory;
DROP VIEW VCategoryPourcents;
DROP VIEW V_PRODUIT;
DROP VIEW V_CATEGORY;
DROP MATERIALIZED VIEW VM_PRODUIT;

-- TABLESPACES
DROP TABLESPACE EXERCICE_TBS;
DROP TABLESPACE tbs_compta;
DROP TABLESPACE tbs_client;

-- USERS
DROP USER USR_BDD;
DROP USER USR_BDD2;
DROP USER USR_TBS;

-- PROFILES
DROP PROFILE profile1;
DROP PROFILE app_user;