-- TABLES
DROP TABLE SYSTEM.TD_PRODUCED_BY;
DROP TABLE SYSTEM.TD_COMPOSED_OF;
DROP TABLE SYSTEM.TD_PLAYLIST;
DROP TABLE SYSTEM.TD_LISTENING;
DROP TABLE SYSTEM.TD_SONG;
DROP TABLE SYSTEM.TD_AUDITOR;
DROP TABLE SYSTEM.TD_ALBUM;
DROP TABLE SYSTEM.TD_ARTIST;


