-- TABLES
DROP TABLE SYSTEM.TD_PRODUCED_BY;
DROP TABLE SYSTEM.TD_COMPOSED_OF;
DROP TABLE SYSTEM.TD_PLAYLIST;
DROP TABLE SYSTEM.TD_LISTENING;
DROP TABLE SYSTEM.TD_SONG;
DROP TABLE SYSTEM.TD_AUDITOR;
DROP TABLE SYSTEM.TD_ALBUM;
DROP TABLE SYSTEM.TD_ARTIST;

-- USERS
DROP USER TD_ADMIN;
DROP USER TD_PRODUCER;
DROP USER TD_ARTIST;
DROP USER TD_AUDITOR;

-- TABLESPACES
DROP TABLESPACE TD_TBS_LABELS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TD_TBS_CLIENTS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TD_TBS_USERDATA INCLUDING CONTENTS AND DATAFILES;