-- PRODUITS
TRUNCATE TABLE PRODUITS;
DROP TABLE PRODUITS;

-- CATEGORIES
TRUNCATE TABLE CATEGORIES;
DROP TABLE CATEGORIES;

-- VIEWS
DROP VIEW VCategory;
DROP VIEW VCategoryPourcents;

-- TABLESPACE
DROP TABLESPACE EXERCICE_TBS;
DROP TABLESPACE tbs_compta;
DROP TABLESPACE tbs_client;