-- PRIVILEGES
REVOKE CREATE SESSION FROM TD_USER_ADMIN;
REVOKE CREATE SESSION FROM TD_USER_PRODUCER;
REVOKE CREATE SESSION FROM TD_USER_ARTIST;
REVOKE CREATE SESSION FROM TD_USER_AUDITOR;

REVOKE CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE FROM TD_ROLE_ADMIN;
REVOKE SELECT ANY TABLE, UPDATE ANY TABLE, INSERT ANY TABLE, DELETE ANY TABLE FROM TD_ROLE_ADMIN;

REVOKE SELECT ON SYSTEM.TD_ARTIST FROM TD_ROLE_CLIENT;
REVOKE SELECT ON SYSTEM.TD_ALBUM FROM TD_ROLE_CLIENT;
REVOKE SELECT ON SYSTEM.TD_AUDITOR FROM TD_ROLE_CLIENT;
REVOKE SELECT ON SYSTEM.TD_SONG FROM TD_ROLE_CLIENT;
REVOKE SELECT ON SYSTEM.TD_LISTENING FROM TD_ROLE_CLIENT;
REVOKE SELECT ON SYSTEM.TD_PRODUCED_BY FROM TD_ROLE_CLIENT;

REVOKE SELECT, INSERT ON SYSTEM.TD_ARTIST FROM TD_USER_PRODUCER;
REVOKE SELECT, INSERT ON SYSTEM.TD_ALBUM FROM TD_USER_PRODUCER;
REVOKE SELECT, INSERT ON SYSTEM.TD_SONG FROM TD_USER_PRODUCER;
REVOKE SELECT, INSERT ON SYSTEM.TD_PRODUCED_BY FROM TD_USER_PRODUCER;

REVOKE SELECT, INSERT, UPDATE, DELETE ON SYSTEM.TD_ARTIST FROM TD_USER_ARTIST;

REVOKE SELECT, INSERT, UPDATE, DELETE ON SYSTEM.TD_AUDITOR FROM TD_USER_AUDITOR;
REVOKE SELECT, INSERT, UPDATE, DELETE ON SYSTEM.TD_PLAYLIST FROM TD_USER_AUDITOR;

-- ROLES
DROP ROLE TD_ROLE_ADMIN;
DROP ROLE TD_ROLE_CLIENT;

-- USERS
DROP USER TD_USER_ADMIN;
DROP USER TD_USER_PRODUCER;
DROP USER TD_USER_ARTIST;
DROP USER TD_USER_AUDITOR;

-- TABLES
DROP TABLE SYSTEM.TD_PRODUCED_BY;
DROP TABLE SYSTEM.TD_COMPOSED_OF;
DROP TABLE SYSTEM.TD_PLAYLIST;
DROP TABLE SYSTEM.TD_LISTENING;
DROP TABLE SYSTEM.TD_SONG;
DROP TABLE SYSTEM.TD_AUDITOR;
DROP TABLE SYSTEM.TD_ALBUM;
DROP TABLE SYSTEM.TD_ARTIST;

-- TABLESPACES
DROP TABLESPACE TD_TBS_LABELS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TD_TBS_CLIENTS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TD_TBS_USERDATA INCLUDING CONTENTS AND DATAFILES;