-- CATEGORIES
INSERT INTO CATEGORIES (category_name)
VALUES ('iphone');

INSERT INTO CATEGORIES (category_name)
VALUES ('iphone +');

-- PRODUITS
INSERT INTO PRODUITS (produit_name, produit_category, produit_price, produit_stock)
VALUES ('iphone 13', 10, 958, 10);

INSERT INTO PRODUITS (produit_name, produit_category, produit_price, produit_stock)
VALUES ('iphone X', 10, 1050, 250);

INSERT INTO PRODUITS (produit_name, produit_category, produit_price, produit_stock)
VALUES ('iphone 13', 20, 2272, 500);

-- FACTURES
INSERT INTO FACTURE (NOM_CLIENT, DATE_FACTURE, MONTANT)
VALUES ('TEST', SYSDATE, 1000);

INSERT INTO FACTURE (NOM_CLIENT, DATE_FACTURE, MONTANT)
VALUES ('FOO', SYSDATE, 5000);

INSERT INTO FACTURE (NOM_CLIENT, DATE_FACTURE, MONTANT)
VALUES ('BAR', SYSDATE, 200);

-- CLIENTS
INSERT INTO CLIENT (NOM, PRENOM, DATE_CREATION)
VALUES ('TEST', 'Test', SYSDATE);

INSERT INTO CLIENT (NOM, PRENOM, DATE_CREATION)
VALUES ('TEST', 'Test', SYSDATE);

INSERT INTO CLIENT (NOM, PRENOM, DATE_CREATION)
VALUES ('TEST', 'Test', SYSDATE);

UPDATE SYSTEM.PRODUITS
SET PRODUIT_STOCK = 0;

COMMIT WORK;