-- Author: Victor BETSCH
-- Date: 2022/11/29
-- Name: Exercice finale
-- Version: 1

-- USERS
CREATE USER LOG_ADMIN IDENTIFIED BY logadm1n;
CREATE USER LOG_USER IDENTIFIED BY logus3r;

CREATE USER COM_ADMIN IDENTIFIED BY c0m4dm1n;
CREATE USER COM_USER1 IDENTIFIED BY c0mus3r1;
CREATE USER COM_USER2 IDENTIFIED BY c0mus3r2;

CREATE USER RH_USER IDENTIFIED BY rhus3r;

-- TABLESPACES
CREATE TABLESPACE tablespace_log
    DATAFILE 'ts_log.dbf' SIZE 10M ONLINE;

CREATE TABLESPACE tablespace_com
    DATAFILE 'ts_com.dbf' SIZE 10M ONLINE;

CREATE TABLESPACE tablespace_rh
    DATAFILE 'ts_rh.dbf' SIZE 10M ONLINE;

CREATE TEMPORARY TABLESPACE tablespace_temp
    TEMPFILE 'temp.dbf' SIZE 10M;


ALTER USER LOG_ADMIN
    DEFAULT TABLESPACE tablespace_log
    TEMPORARY TABLESPACE tablespace_temp;

ALTER USER LOG_USER
    DEFAULT TABLESPACE tablespace_log
    TEMPORARY TABLESPACE tablespace_temp;

ALTER USER COM_ADMIN
    DEFAULT TABLESPACE tablespace_com
    TEMPORARY TABLESPACE tablespace_temp;

ALTER USER COM_USER1
    DEFAULT TABLESPACE tablespace_com
    TEMPORARY TABLESPACE tablespace_temp;

ALTER USER COM_USER2
    DEFAULT TABLESPACE tablespace_com
    TEMPORARY TABLESPACE tablespace_temp;

ALTER USER RH_USER
    DEFAULT TABLESPACE tablespace_rh
    TEMPORARY TABLESPACE tablespace_temp;


-- PROFILES
CREATE PROFILE system LIMIT
    SESSIONS_PER_USER 8
    CPU_PER_SESSION UNLIMITED
    CPU_PER_CALL 2000
    CONNECT_TIME 200
    IDLE_TIME 10;

CREATE PROFILE passwords LIMIT
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 30
    PASSWORD_REUSE_TIME 60
    PASSWORD_REUSE_MAX 2
    PASSWORD_LOCK_TIME 5
    PASSWORD_GRACE_TIME 7;