-- USERS
DROP USER LOG_ADMIN;
DROP USER LOG_USER;

DROP USER COM_ADMIN;
DROP USER COM_USER1;
DROP USER COM_USER2;

DROP USER RH_USER;

-- TABLESPACES
DROP TABLESPACE tablespace_log INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_com INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_rh INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_temp INCLUDING CONTENTS AND DATAFILES;