-- USERS
DROP USER LOG_ADMIN;
DROP USER LOG_USER;

DROP USER COM_ADMIN;
DROP USER COM_USER1;
DROP USER COM_USER2;

DROP USER RH_USER;

-- TABLESPACES
DROP TABLESPACE tablespace_log;
DROP TABLESPACE tablespace_com;
DROP TABLESPACE tablespace_rh;