-- Author: Victor BETSCH
-- Date: 2022/11/29
-- Name: Exercice finale
-- Version: 1

-- USERS
CREATE USER LOG_ADMIN IDENTIFIED BY logadm1n;
CREATE USER LOG_USER IDENTIFIED BY logus3r;

CREATE USER COM_ADMIN IDENTIFIED BY c0m4dm1n;
CREATE USER COM_USER1 IDENTIFIED BY c0mus3r1;
CREATE USER COM_USER2 IDENTIFIED BY c0mus3r2;

CREATE USER RH_USER IDENTIFIED BY rhus3r;


-- TABLESPACES
CREATE TABLESPACE tablespace_log
    DATAFILE 'logistic.dbf' SIZE 10M
    ONLINE;

CREATE TEMPORARY TABLESPACE tablespace_com
    TEMPFILE 'marketing.dbf' SIZE 10M;

CREATE UNDO TABLESPACE tablespace_rh
    DATAFILE 'rh.dbf' SIZE 10M;