-- TABLESPACES
DROP TABLESPACE tablespace_log INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_com INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_rh INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE tablespace_temp INCLUDING CONTENTS AND DATAFILES;

-- USERS
DROP USER LOG_ADMIN;
DROP USER LOG_USER;

DROP USER COM_ADMIN;
DROP USER COM_USER1;
DROP USER COM_USER2;

DROP USER RH_USER;

-- TABLES
DROP TABLE XDB.COM_PRODUCTS;
DROP TABLE XDB.COM_FACTURES;
DROP TABLE XDB.RH_CLIENT;


-- PROFILES
DROP PROFILE system;
DROP PROFILE passwords;

/*
-- ROLES
DROP ROLE logistic;
DROP ROLE marketing;
DROP ROLE human_resources;
*/
