-- FUNCTIONS
CREATE OR REPLACE FUNCTION F_POURCENTS(a NUMBER, b NUMBER)
RETURN NUMBER IS
BEGIN
	RETURN (a * 100) / b;
END;

CREATE OR REPLACE FUNCTION F_STOCK_ARTICLE(id_produit IN INT)
RETURN VARCHAR2(255) IS stock VARCHAR2(255);
-- TO REVIEW
BEGIN
    SELECT TO_CHAR(PRODUIT_STOCK) INTO stock FROM PRODUITS WHERE PRODUIT_ID = id_produit;
    RETURN stock;
END;

-- TEST FUNCTIONS
SELECT F_POURCENTS(1, 100) FROM DUAL;
SELECT F_STOCK_ARTICLE(2) FROM DUAL;