CREATE TABLE PRODUITS (
    produit_id NUMERIC(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produit_name VARCHAR(64),
    produit_category NUMERIC(8) NOT NULL,
    produit_price NUMERIC(8,2) NOT NULL,
    produit_stock NUMERIC(8) NULL
);