CREATE TABLE PRODUITS (
    produit_id NUMERIC(8) GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    produit_name VARCHAR(64),
    produit_category NUMERIC(8) NOT NULL,
    produit_price NUMERIC(8,2) NOT NULL,
    produit_stock NUMERIC(8) NULL,
    CONSTRAINT products_category_fk FOREIGN KEY (produit_category)
        REFERENCES CATEGORIES(category_id)
);