CREATE TABLE FACTURE (
    id INT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    nom_client VARCHAR(32),
    date_facture DATE,
    montant INT
)
TABLESPACE tbs_compta;

CREATE TABLE CLIENT (
    id INT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    nom VARCHAR(32),
    prenom VARCHAR(32),
    date_creation DATE
)
TABLESPACE tbs_client;