-- CLEAR
DROP ROLE client_G;
DROP ROLE compta_G;
DROP ROLE client;
DROP ROLE compta;
DROP ROLE client_A;
DROP ROLE compta_A;
DROP ROLE ADMIN;

DROP USER usr_client_1;
DROP USER usr_compta_1;
DROP USER usr_client_admin;
DROP USER usr_compta_admin;
DROP USER ADMINBDD_DBA;

-- ROLES
CREATE ROLE client_G IDENTIFIED EXTERNALLY;
CREATE ROLE compta_G IDENTIFIED EXTERNALLY;

CREATE ROLE client IDENTIFIED EXTERNALLY;
CREATE ROLE compta IDENTIFIED EXTERNALLY;
CREATE ROLE client_A IDENTIFIED EXTERNALLY;
CREATE ROLE compta_A IDENTIFIED EXTERNALLY;

CREATE ROLE ADMIN IDENTIFIED EXTERNALLY;

-- USERS
CREATE USER usr_client_1 IDENTIFIED BY client1;
CREATE USER usr_compta_1 IDENTIFIED BY compta1;
CREATE USER usr_client_admin IDENTIFIED BY clientA;
CREATE USER usr_compta_admin IDENTIFIED BY comptaA;

CREATE USER ADMINBDD_DBA IDENTIFIED BY ADMIN;

-- SESSIONS
GRANT CREATE SESSION TO usr_client_1;
GRANT CREATE SESSION TO usr_compta_1;
GRANT CREATE SESSION TO usr_client_admin;
GRANT CREATE SESSION TO usr_compta_admin;

GRANT CREATE SESSION TO ADMINBDD_DBA;

-- PRIVILEGES
GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENT TO client;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE TO client_A;
GRANT SELECT, UPDATE, INSERT, DELETE ON FACTURE TO compta;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE TO compta_A;