CREATE USER USR_BDD
    IDENTIFIED BY USR_BDD;

ALTER USER USR_BDD
    ACCOUNT LOCK;

CREATE USER USR_BDD2
    IDENTIFIED BY USR_BDD2
    DEFAULT TABLESPACE TBS_CLIENT
    TEMPORARY TABLESPACE EXERCICE2_TBS
    QUOTA 100K ON TBS_COMPTA
    PASSWORD EXPIRE
    ACCOUNT UNLOCK;

ALTER USER USR_BDD
    IDENTIFIED BY NEW;

DROP USER USR_BDD CASCADE;

ALTER USER USR_BDD2
    QUOTA 50K ON TBS_COMPTA;

ALTER USER USR_BDD2
    DEFAULT TABLESPACE TBS_COMPTA;

-- PRIVILEGES

GRANT CREATE SESSION TO USR_BDD, USR_BDD2;

GRANT CREATE TABLE, ALTER ANY TABLE TO USR_BDD2;

GRANT DROP TABLESPACE TO USR_BDD2;

GRANT CREATE TABLE TO USR_BDD;

REVOKE DROP TABLESPACE FROM USR_BDD2;

CREATE USER USR_TBS
    IDENTIFIED BY USR_TBS;
GRANT CREATE TABLESPACE, ALTER TABLESPACE, DROP TABLESPACE, UNLIMITED TABLESPACE TO USR_TBS;

GRANT SELECT, DELETE, ALTER ON PRODUITS TO USR_BDD2;
GRANT SELECT, DELETE, ALTER ON CATEGORIES TO USR_BDD2;

GRANT UPDATE(CATEGORY_NAME) ON CATEGORIES TO USR_BDD2;
GRANT UPDATE(PRODUIT_NAME, PRODUIT_STOCK) ON PRODUITS TO USR_BDD2;

GRANT REFERENCES ON CLIENT TO USR_BDD2;
GRANT REFERENCES ON FACTURE TO USR_BDD2;