-- ADMIN BDD TD final - DEV B
-- Auteur: Victor BETSCH
-- Date de rendue maximum : 06/12/2022 à 18h
-- Coefficient : 3
-- Temps conseillé : 8h
-- Sujet choisi: Plateforme de musiques (SpotHiFi)

-- ARTISTES
INSERT INTO SYSTEM.TD_ARTIST (NAME)
VALUES ('Nick Johnson');

INSERT INTO SYSTEM.TD_ARTIST (NAME)
VALUES ('Omar Freddy');

INSERT INTO SYSTEM.TD_ARTIST (NAME)
VALUES ('John Winston');

INSERT INTO SYSTEM.TD_ARTIST (NAME)
VALUES ('American Savage');

INSERT INTO SYSTEM.TD_ARTIST (NAME)
VALUES ('Twitty Bob');


-- ALBUMS
INSERT INTO SYSTEM.TD_ALBUM (NAME, RELEASE_DATE)
VALUES ('The Fall Of Kingdom', DATE '2018-06-03');

INSERT INTO SYSTEM.TD_ALBUM (NAME, RELEASE_DATE)
VALUES ('Image Rising', DATE '1990-03-06');

INSERT INTO SYSTEM.TD_ALBUM (NAME, RELEASE_DATE)
VALUES ('Thunsand Reasons', DATE '2020-04-12');

INSERT INTO SYSTEM.TD_ALBUM (NAME, RELEASE_DATE)
VALUES ('Magnific', DATE '2021-12-04');

INSERT INTO SYSTEM.TD_ALBUM (NAME, RELEASE_DATE)
VALUES ('Sunset To Sunrise', DATE '2015-09-17');


-- AUDITORS
INSERT INTO SYSTEM.TD_AUDITOR (NAME, MAIL, AGE, COUNTRY)
VALUES ('Mister Music', 'mister.music@gmail.com', 15, 'Denmark');

INSERT INTO SYSTEM.TD_AUDITOR (NAME, MAIL, AGE, COUNTRY)
VALUES ('Rosa Parc', 'rosa.parc@gmail.com', 18, 'England');

INSERT INTO SYSTEM.TD_AUDITOR (NAME, MAIL, AGE, COUNTRY)
VALUES ('John Woody', 'john.woody@gmail.com', 16, 'USA');

INSERT INTO SYSTEM.TD_AUDITOR (NAME, MAIL, AGE, COUNTRY)
VALUES ('Sarah Flisher', 'sarah.flisher@gmail.it', 22, 'Italy');

INSERT INTO SYSTEM.TD_AUDITOR (NAME, MAIL, AGE, COUNTRY)
VALUES ('Frank Dehrzdring', 'frank.dehrzdring@gmail.de', 15, 'Germany');


-- SONGS
INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('Surprise', 2.99, 2);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (1, 2);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('Not Surprised', 2.99, 2);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (2, 1);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (2, 2);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('The reason to smile', 3.25, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (3, 3);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('The reason to death', 3.25, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (4, 4);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (4, 5);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('The reason to joy', 3.25, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (5, 5);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('The reason to sob', 3.25, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (6, 3);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('Earth Quake', 1.56, 1);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (7, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (7, 4);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('Ouragan', 1.56, 1);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (8, 2);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (8, 4);

INSERT INTO SYSTEM.TD_SONG (NAME, PRICE, ALBUM_ID)
VALUES ('Tornado', 1.56, 1);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (9, 2);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (9, 3);

INSERT INTO SYSTEM.TD_PRODUCED_BY (SONG_ID, ARTIST_ID)
VALUES (9, 4);


-- LISTENINGS
INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (1, 2, DATE '2022-11-09');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (1, 3, DATE '2021-11-09');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (2, 1, DATE '2020-11-09');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (2, 3, DATE '2019-10-08');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (2, 5, DATE '2020-08-10');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (3, 7, DATE '2020-10-08');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (3, 8, DATE '2020-09-11');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (3, 3, DATE '2020-04-09');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (3, 1, DATE '2020-09-04');

INSERT INTO SYSTEM.TD_LISTENING (AUDITOR_ID, SONG_ID, LISTEN_DATE)
VALUES (3, 2, DATE '2020-05-02');


-- PLAYLISTS
INSERT INTO SYSTEM.TD_PLAYLIST (NAME, AUDITOR_ID)
VALUES ('LOOOOVE', 4);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (1, 1);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (1, 2);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (1, 3);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (1, 4);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (1, 5);

INSERT INTO SYSTEM.TD_PLAYLIST (NAME, AUDITOR_ID)
VALUES ('Chill', 2);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (2, 3);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (2, 7);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (2, 6);

INSERT INTO SYSTEM.TD_PLAYLIST (NAME, AUDITOR_ID)
VALUES ('Rock', 3);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (3, 3);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (3, 8);

INSERT INTO SYSTEM.TD_PLAYLIST (NAME, AUDITOR_ID)
VALUES ('Rap', 2);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (4, 9);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (4, 7);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (4, 6);

INSERT INTO SYSTEM.TD_COMPOSED_OF (PLAYLIST_ID, SONG_ID)
VALUES (4, 5);

-- COMMIT TRANSACTIONS
COMMIT WORK;